/**
 * Write one static HTML document per route, per language.
 *
 * This is the step that makes the site cheap. The Next.js version it replaces sent a
 * 14 KB shell, ~880 KB of JavaScript across ten chunks, and then reconstructed the
 * page in the browser before anything was legible. Here the markup is final by the
 * time it leaves nginx: the CSS is the only render-blocking request, and the single
 * ~1 KB script is deferred and does nothing a reader waits on.
 *
 * Rendering twice — French at the root, English under /en/ — is also what keeps the
 * second language free: a visitor downloads one finished document and never the
 * dictionary for the other.
 *
 * Three inputs come together:
 *   - .ssr/entry.js, the Svelte components compiled for the server, which supplies
 *     the body markup for a given locale;
 *   - dist/.vite/manifest.json, which names the hashed client asset files;
 *   - the route table in src/lib/site.ts, which is now two documents and supplies
 *     their paths, titles and descriptions.
 *
 * It also emits robots.txt, a bilingual sitemap, a 404 document per language, and the
 * CSP hash of the inline theme script — see writeCspHash.
 *
 * And it checks its own output — see assertDocument. That is where the guarantees
 * that types cannot express are actually enforced.
 */

import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  THEME_SCRIPT,
  documentFor,
  stripHydrationMarkers,
} from "./document.mjs";

const FRONTEND = fileURLToPath(new URL("..", import.meta.url));
const ROOT = join(FRONTEND, "..");
const DIST = join(FRONTEND, "dist");
const SSR_ENTRY = join(FRONTEND, ".ssr", "entry.js");
const MANIFEST = join(DIST, ".vite", "manifest.json");
const CSP_SNIPPET = join(ROOT, "deploy", "csp-script-hash.conf");

/**
 * Resolve the hashed client asset names from the Vite manifest.
 *
 * @returns {Promise<{script: string, styles: string[]}>}
 */
async function readAssets() {
  const manifest = JSON.parse(await readFile(MANIFEST, "utf8"));
  const chunks = Object.values(manifest);
  const entry = chunks.find((chunk) => chunk.isEntry);
  if (!entry) {
    throw new Error(
      `no entry chunk in ${MANIFEST} — did the client build run?`,
    );
  }

  // Two shapes to cover. With code splitting on, Vite lists a chunk's stylesheets in
  // its own `css` array; with `cssCodeSplit: false` — what this build uses, since the
  // pages share one layout — the single stylesheet becomes a top-level `style.css`
  // entry instead, and reading only `entry.css` would silently produce unstyled pages.
  const styles = new Set((entry.css ?? []).map((file) => `/${file}`));
  for (const chunk of chunks) {
    if (chunk.file?.endsWith(".css")) styles.add(`/${chunk.file}`);
  }
  if (styles.size === 0) {
    throw new Error(
      `no stylesheet in ${MANIFEST} — the pages would render unstyled`,
    );
  }

  return { script: `/${entry.file}`, styles: [...styles] };
}

/**
 * Write the CSP source expression for the inline theme script.
 *
 * The template's selling point is a Content-Security-Policy with no 'unsafe-inline',
 * and the anti-flash script has to be inline to run before paint. A hash is the way to
 * keep both: nginx allow-lists this exact script and nothing else.
 *
 * Dockerfile.web copies this file out of the build stage rather than from the repo, so
 * the header always matches the script actually in the page — a stale committed hash
 * cannot silently block it.
 *
 * @param {string} hash The sha256-... source expression.
 */
async function writeCspHash(hash) {
  const contents = `# Generated by frontend/scripts/prerender.mjs — do not edit.
#
# sha256 of the inline theme script the prerenderer puts in every <head>. It runs
# before first paint to apply the saved theme, so it cannot be moved to an external
# file without reintroducing the flash it exists to prevent.
#
# A map rather than a plain variable: nginx has no 'set' at http level, and
# security-headers.conf is included inside location blocks, which is too late.
map $host $csp_script_hash {
    default "${hash}";
}
`;
  await writeFile(CSP_SNIPPET, contents);
}

/**
 * Emit robots.txt and a sitemap covering both languages.
 *
 * Each <url> carries its alternates, which is what tells a crawler that the two
 * documents are one page in two languages rather than duplicate content.
 *
 * @param {object[]} routes Every document, one per locale.
 * @param {() => {locale: string, href: string}[]} alternatesFor
 * @param {string} siteUrl
 */
async function writeCrawlerFiles(routes, alternatesFor, siteUrl) {
  await writeFile(
    join(DIST, "robots.txt"),
    `User-agent: *\nAllow: /\n\nSitemap: ${siteUrl}/sitemap.xml\n`,
  );

  const urls = routes
    .map((route) => {
      const links = alternatesFor()
        .map(
          (alternate) =>
            `    <xhtml:link rel="alternate" hreflang="${alternate.locale}" href="${alternate.href}"/>`,
        )
        .join("\n");
      return `  <url>\n    <loc>${siteUrl}${route.path}</loc>\n${links}\n  </url>`;
    })
    .join("\n");

  await writeFile(
    join(DIST, "sitemap.xml"),
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
      `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n` +
      `        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n${urls}\n</urlset>\n`,
  );
}

// Em dash and en dash as separators, and a colon introducing a clause. The same house
// rule tests/test_api.py enforces on content.py, applied here to the finished text
// instead — which is the only place that also covers the interface strings in
// lib/i18n.ts and anything written directly into a component.
const FORBIDDEN_PUNCTUATION = [
  ["\u2014", "em dash"],
  ["\u2013", "en dash"],
  [" : ", "spaced colon"],
];

/**
 * Check a finished document against the promises the source cannot keep on its own.
 *
 * Three of these exist because TypeScript looked like it was checking them and was
 * not. `SectionId` is `keyof` a hand-written interface, so a section added in
 * backend/content.py and exported to JSON type-checks, tests clean, and renders
 * nowhere at all. The build is the first place that can tell, because it is the first
 * place holding the actual page.
 *
 * @param {string} html A complete document.
 * @param {object} context Section ids, nav links and the paths that must resolve.
 * @param {string} label What to name in the error.
 */
function assertDocument(html, context, label) {
  const problems = [];

  const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));

  // A section declared in the content but never placed on the page.
  for (const id of context.sectionIds) {
    if (!ids.has(id)) {
      problems.push(
        `section "${id}" is in content.sections but has no element on the page`,
      );
    }
  }

  // A nav link pointing at an anchor that does not exist is a link that does nothing.
  for (const link of context.navLinks) {
    const anchor = link.href.replace(/^#/, "");
    if (!ids.has(anchor)) {
      problems.push(`the nav links to #${anchor}, which no element carries`);
    }
  }

  // Text between tags only: an https:// in an href is not prose.
  const text = [...html.matchAll(/>([^<]+)</g)].map((m) => m[1]).join(" ");
  for (const [token, name] of FORBIDDEN_PUNCTUATION) {
    const at = text.indexOf(token);
    if (at !== -1) {
      problems.push(
        `${name} in the rendered text, near "${text.slice(Math.max(0, at - 40), at + 20).trim()}"`,
      );
    }
  }

  // Every image the markup names has to be a file that exists, in every variant the
  // srcset offers. `just images` writing one width and not the other used to be
  // invisible until a 2x screen asked for the missing one.
  const referenced = new Set();
  for (const match of html.matchAll(/(?:src|srcset)="([^"]+)"/g)) {
    for (const candidate of match[1].split(",")) {
      const path = candidate.trim().split(/\s+/)[0];
      if (path.startsWith("/images/") || path.startsWith("/fonts/")) {
        referenced.add(path);
      }
    }
  }
  for (const path of referenced) {
    if (!existsSync(join(DIST, path))) {
      problems.push(
        `${path} is referenced but was never written — run \`just images\``,
      );
    }
  }

  if (problems.length > 0) {
    throw new Error(`${label}:\n  ${problems.join("\n  ")}`);
  }
}

async function prerender() {
  const entry = await import(pathToFileURL(SSR_ENTRY).href);
  const {
    renderRoute,
    routes,
    siteName,
    alternates,
    notFoundMeta,
    navigation,
    SECTION_IDS,
    localePrefix,
    LOCALES,
    DEFAULT_LOCALE,
    SITE_URL,
    OG_IMAGE,
  } = entry;
  const site = { SITE_URL, siteName, OG_IMAGE };
  const assets = await readAssets();

  const written = [];

  for (const route of routes) {
    const links = alternates();
    const rendered = renderRoute(route.locale);
    const html = documentFor(
      {
        ...route,
        alternates: links,
        // x-default is the version to serve when no language matches, which for this
        // site is French: the audience and the freelance market are French.
        defaultHref: links.find((link) => link.locale === DEFAULT_LOCALE)?.href,
      },
      { body: stripHydrationMarkers(rendered.body), head: rendered.head },
      assets,
      site,
    );
    assertDocument(
      html,
      { sectionIds: SECTION_IDS, navLinks: navigation(route.locale) },
      `${route.file} is not the page it claims to be`,
    );
    const target = join(DIST, route.file);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, html);
    written.push([route.file, Buffer.byteLength(html)]);
  }

  // One 404 per language, so an English visitor who mistypes a URL does not land on a
  // French error page. Rendered through the same shell, so a wrong URL still lands on
  // the site rather than on nginx's default page.
  for (const locale of LOCALES) {
    const prefix = localePrefix(locale).slice(1);
    const rendered = renderRoute(locale, true);
    const html = documentFor(
      {
        locale,
        path: `${localePrefix(locale)}/404`,
        ...notFoundMeta(locale),
        alternates: [],
      },
      { body: stripHydrationMarkers(rendered.body), head: rendered.head },
      assets,
      site,
    );
    // The 404 carries the header, so its nav must resolve too — but to the page it
    // links away to, not to itself, so only the punctuation and the assets are
    // checked here.
    assertDocument(html, { sectionIds: [], navLinks: [] }, `${locale} 404`);
    const file = prefix ? `${prefix}/404.html` : "404.html";
    const target = join(DIST, file);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, html);
    written.push([file, Buffer.byteLength(html)]);
  }

  await writeCrawlerFiles(routes, alternates, SITE_URL);

  const hash = `sha256-${createHash("sha256").update(THEME_SCRIPT).digest("base64")}`;
  await writeCspHash(hash);

  for (const [file, bytes] of written) {
    console.log(
      `  ${file.padEnd(24)} ${(bytes / 1024).toFixed(1).padStart(6)} KB`,
    );
  }
  console.log(`  csp script hash          ${hash}`);
}

await prerender();
