import raw from "../data/content.json";
import imageManifest from "../data/images.json";
import type { AchievementKind, Period, TestimonialKind, Text } from "./i18n";

/**
 * Typed access to the content Python exported.
 *
 * content.json is generated by `just content` from backend/content.py and committed,
 * which is what lets Dockerfile.web build the site without a Python interpreter. The
 * interfaces below restate its shape so the templates get checked; `just check`
 * regenerates the JSON and fails on a diff, so the two cannot drift silently.
 *
 * Every visible string is a `Text` carrying both languages — see lib/i18n.ts.
 */

export interface SocialLink {
  platform: string;
  href: string;
  icon: string;
}

export interface Project {
  title: string;
  description: Text;
  image: string;
  link: string;
  stack: string[];
  repository: string | null;
  article: Text | null;
}

export interface Achievement {
  title: Text;
  description: Text;
  kind: AchievementKind;
  period: Period | null;
  url: string | null;
}

export interface TimelineEntry {
  year: number;
  achievements: Achievement[];
}

export interface ContactMethod {
  label: Text;
  value: string;
  href: string;
}

export interface LanguageSkill {
  name: Text;
  level: Text | null;
}

export interface SkillGroup {
  name: Text;
  items: Text[];
}

export interface Testimonial {
  quote: Text;
  author: string;
  kind: TestimonialKind;
  published: string;
  role: string | null;
  company: string | null;
  rating: number | null;
  source: string;
  source_url: string | null;
}

export interface Profile {
  name: string;
  role: Text;
  location: string;
  headline: Text;
  summary: Text;
  about: Text;
}

export interface SectionCopy {
  heading: Text;
  subheading: Text;
  paragraph: Text;
}

/** Keys are the section ids in lib/site.ts, so the two cannot drift apart. */
export interface Sections {
  about: SectionCopy;
  projects: SectionCopy;
  skills: SectionCopy;
  timeline: SectionCopy;
  testimonial: SectionCopy;
  contact: SectionCopy;
}

export interface Content {
  profile: Profile;
  socials: SocialLink[];
  projects: Project[];
  timeline: TimelineEntry[];
  contact: ContactMethod[];
  skills: SkillGroup[];
  languages: LanguageSkill[];
  testimonials: Testimonial[];
  sections: Sections;
}

// `as Content` rather than a plain annotation: TypeScript widens every string in an
// imported JSON module to `string`, so `kind` arrives as a string instead of the union
// it actually holds. The narrowing is safe because the value is produced by
// backend/content.py, where `kind` is a msgspec `Literal` and a wrong value cannot be
// constructed in the first place.
export const content = raw as Content;

export interface ImageTarget {
  width: number;
  height: number;
  widths: number[];
  formats: string[];
}

/** Written by `just images`, so the markup never hardcodes a width the encoder did
 *  not actually emit. */
export const images: Record<"cards" | "avatar", ImageTarget> = imageManifest;
